#pragma once

//messages are numbered with unique ID and this message translated text are  stored on en.dat and tr.dat files
#define welcome_to_my_program 1
#define lets_translate_messages 2
#define current_lang_setting 3
#define enter_language_option 4
#define Calculate_Bill 5
#define Add_Goods 6
#define Edit_Goodss 7
#define Display_All 8
#define Search 9
#define Delete_Goods 10
#define Exit 11
#define Change_Language 12
#define MAIN_MENU 13
#define SEARCH_MENU 14
#define By_Code 15
#define By_Rate 16
#define By_Quantity 17
#define Back_to_main_menu 18
#define     aca 19
#define enter_end_to_finish_input 20
#define enter_item_code 21
#define enter_quantity 22
#define TOTAL_AMOUNT 23
#define FASHION_WEAR 24
#define Departmental_Store 25
#define CUSTOMERS_BILL 26
#define SN____Item_Name_____Quantity______Rate____________Total 27
#define Enter_new_record_Y_N 28
#define Enter_rate_of_the_item 29
#define Enter_quantity_of_the_item 30
#define Enter_name_of_the_item 31
#define ADD_ARTICLES 32
#define Enter_new_code_of_the_article 33
#define code_already_exists 34
#define enter_again 35
#define EDIT_RECORDS 36
#define name________s 37
#define code________s 38
#define rate________g 39
#define quantity____d 40
#define Do_you_want_to_edit_this_record__y_n 41
#define edit_name_1 42
#define edit_code_2 43
#define edit_rate_3 44
#define edit_quantity_4 45
#define enter_your_choice_1_2_3_4 46
#define enter_new_name 47
#define enter_new_rate 48
#define enter_new_quantity 49
#define ____item_edited 50
#define Item_does_not_exist 51
#define TRY_AGAIN 52
#define Press_any_key_to_see_more 53
#define no_articles_found 54
#define Enter_lower_range 55
#define Enter_upper_range 56
#define No_items_found 57
#define enter_lower_range 58
#define enter_upper_range 59
#define no_item_found 60
#define Departmental_Store 61
#define RECORDS 62
#define SN___Item_Name___Item_Code______Rate_____Quantity 63
#define DELETE_ARTICLES 64
#define item_deleted 65
#define item_does_not_exist 66
#define CHANGE_LANGUAGE 67
#define for_english_press 68
#define turkce_icin_1_e_basin 69
#define enter_your_choice_then_press_enter 70